### ISSUE TITLE
Install failed - with readme instruction on MacOS 14.7.5

### ISSUE THREAD

**Issue by RIOH-Inc** [Dadoum/pyprovision#16]
I do receive this error on install :

../../.dub/packages/provision/645d56d8e8c86c057893321843db00b21f1aaeb2/provision/lib/provision/adi.d(475,24): Error: cannot modify expression `this.request.headers()["X-Apple-I-Client-Time"]` because it is not an lvalue
              request.headers["X-Apple-I-Client-Time"] = Clock.currTime().stripMilliseconds().toISOExtString();

Followed up the readme to install lcd and all things arround

Did use python 3.10.13 for compile, ldc-1.41.0, pip 24.3.1 

Full trace : 

sudo python -m pip install . 
3
WARNING: The directory '/Users/dev/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Processing /Users/dev/pyprovision
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyprovision
  Building wheel for pyprovision (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyprovision (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      Usage:
      ['LICENSE', 'dub', 'pyprovision', 'README.md', 'setup.py', 'example.py', '.gitignore', 'pyprovision.egg-info', 'build', '.git']
      dub build -c python310 -b release
          Starting Performing "release" build using /Users/dev/dlang/ldc-1.41.0/bin/ldc2 for aarch64, arm_hardfloat.
        Up-to-date dynamic-loader ~master: target for configuration [library] is up to date.
        Up-to-date plist-d ~master: target for configuration [dynamic] is up to date.
        Up-to-date automem 0.6.11: target for configuration [library] is up to date.
        Up-to-date cachetools 0.4.2: target for configuration [library] is up to date.
        Up-to-date requests 2.1.3: target for configuration [std] is up to date.
        Up-to-date slf4d 2.4.3: target for configuration [library] is up to date.
          Building provision ~master: building configuration [libplist]
      ../../.dub/packages/provision/645d56d8e8c86c057893321843db00b21f1aaeb2/provision/lib/provision/adi.d(443,24): Error: cannot modify expression `this.request.headers()["X-Apple-I-Client-Time"]` because it is not an lvalue
              request.headers["X-Apple-I-Client-Time"] = Clock.currTime().stripMilliseconds().toISOExtString();
                             ^
      ../../.dub/packages/provision/645d56d8e8c86c057893321843db00b21f1aaeb2/provision/lib/provision/adi.d(475,24): Error: cannot modify expression `this.request.headers()["X-Apple-I-Client-Time"]` because it is not an lvalue
              request.headers["X-Apple-I-Client-Time"] = Clock.currTime().stripMilliseconds().toISOExtString();
                             ^
      Error /Users/dev/dlang/ldc-1.41.0/bin/ldc2 failed with exit code 1.
      error: command '/Users/dev/dlang/ldc-1.41.0/bin/dub' failed with exit code 2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyprovision
Failed to build pyprovision
ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyprovision)
zsh: command not found: 3

**Comment by liukiti** [comment]
i faced the same problem. but solved in not a clear way. but my guess is this information:[ _"you could install https://github.com/Dadoum/pyprovision (first install anisette-v3-server though to get a nice D environment and the required android libs)"_](https://github.com/biemster/FindMy).

### system then, with same error as yours
- kali 6.12.33+kali-amd64
- Python 3.9.12
- no venv

### system now, with installation success
- debian 6.12.41+deb13-amd64
- Python 3.13.5
- with venv

### list of commands  for reference
- for anisette-v3 recommendations + python3-full  (Python 3.13.5)
```
apt install --no-install-recommends -y ca-certificates ldc git clang dub libz-dev libssl-dev python3-full
``` 
- creating a venv at "~/venv"
```
python3 -m venv ~/venv
``` 
- installing the pyprovision with pip from venv (must be in the pyprovision folder)
```
~/pyprovision$ ~/venv/bin/pip install .
```
- if you need to install python lib/dependencies (xyz), use the pip from the venv
```
~/venv/bin/pip install xyz
```
